version: "3"

services:
  transmission:
    build:
      context: .
      dockerfile: Dockerfile  
    image: icarrilloquero/rpi-transmission
    ports:
      - 9091:9091/tcp
    restart: unless-stopped
    volumes:
      - config:/config
      - /media/usb/downloads/to_download:/to_download
      - /media/usb/downloads/torrents:/output
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - PORT=${PORT}
      - TZ=Europe/Madrid

volumes:
  config:
